server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.215.194:3306/ewlive?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    hikari:
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 100mb
      max-request-size: 100mb
  mail:
    host: smtp.qq.com
    username: 1174716220@qq.com
    password: uuiwvybctwrfiiag
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          ssl:
            enable: true
    default-encoding: UTF-8
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: org.ewlive.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  file: logs/ewlive.log


upload:
      path: E:\\WorkSpace\\IDEA WorkSpace\\upload\\


