server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.215.194:3306/ewlive?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.ewlive.entity

logging:
  file: logs/ewlive.log




